CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id        BIGINT NOT NULL,
    about_me  VARCHAR(500),
    allergies VARCHAR(500),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE dish_ingredients
(
    dish_id       BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    CONSTRAINT pk_dish_ingredients PRIMARY KEY (dish_id, ingredient_id)
);

CREATE TABLE dishes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(500)                            NOT NULL,
    price       DECIMAL(10, 2)                          NOT NULL,
    image_url   VARCHAR(255)                            NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_dishes PRIMARY KEY (id)
);

CREATE TABLE ingredients
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255)                            NOT NULL,
    content VARCHAR(500)                            NOT NULL,
    sent_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE opinions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(500)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    client_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_opinions PRIMARY KEY (id)
);

CREATE TABLE reservation_dishes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity       INTEGER                                 NOT NULL,
    is_served      BOOLEAN                                 NOT NULL,
    reservation_id BIGINT                                  NOT NULL,
    dish_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_reservation_dishes PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_period TSRANGE                                 NOT NULL,
    status             VARCHAR(30)                             NOT NULL,
    table_id           BIGINT                                  NOT NULL,
    client_id          BIGINT                                  NOT NULL,
    waiter_id          BIGINT,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE restaurant_tables
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_number    INTEGER                                 NOT NULL,
    seats           INTEGER                                 NOT NULL,
    row_position    INTEGER                                 NOT NULL,
    column_position INTEGER                                 NOT NULL,
    CONSTRAINT pk_restaurant_tables PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(30)                             NOT NULL,
    last_name     VARCHAR(30)                             NOT NULL,
    phone_number  VARCHAR(9)                              NOT NULL,
    role          VARCHAR(30)                             NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE waiters
(
    id             BIGINT  NOT NULL,
    hire_date      date    NOT NULL,
    speaks_english BOOLEAN NOT NULL,
    CONSTRAINT pk_waiters PRIMARY KEY (id)
);

CREATE TABLE work_shifts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    waiter_id    BIGINT                                  NOT NULL,
    shift_period TSRANGE                                 NOT NULL,
    CONSTRAINT pk_work_shifts PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE ingredients
    ADD CONSTRAINT uc_ingredients_name UNIQUE (name);

ALTER TABLE restaurant_tables
    ADD CONSTRAINT uc_restaurant_tables_tablenumber UNIQUE (table_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE dishes
    ADD CONSTRAINT FK_DISHES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE opinions
    ADD CONSTRAINT FK_OPINIONS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_TABLE FOREIGN KEY (table_id) REFERENCES restaurant_tables (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_WAITER FOREIGN KEY (waiter_id) REFERENCES waiters (id);

ALTER TABLE reservation_dishes
    ADD CONSTRAINT FK_RESERVATION_DISHES_ON_DISH FOREIGN KEY (dish_id) REFERENCES dishes (id);

ALTER TABLE reservation_dishes
    ADD CONSTRAINT FK_RESERVATION_DISHES_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES reservations (id);

ALTER TABLE waiters
    ADD CONSTRAINT FK_WAITERS_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE work_shifts
    ADD CONSTRAINT FK_WORK_SHIFTS_ON_WAITER FOREIGN KEY (waiter_id) REFERENCES waiters (id);

ALTER TABLE dish_ingredients
    ADD CONSTRAINT fk_dising_on_dish FOREIGN KEY (dish_id) REFERENCES dishes (id);

ALTER TABLE dish_ingredients
    ADD CONSTRAINT fk_dising_on_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (id);