CREATE TABLE activation_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_activation_tokens PRIMARY KEY (id)
);

ALTER TABLE activation_tokens
    ADD CONSTRAINT uc_activation_tokens_token UNIQUE (token);

ALTER TABLE activation_tokens
    ADD CONSTRAINT uc_activation_tokens_user UNIQUE (user_id);

ALTER TABLE activation_tokens
    ADD CONSTRAINT FK_ACTIVATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);